

import java.sql.*;

import javax.swing.JOptionPane;

public class NewMember extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewMember() {
        initComponents();

        try {
            int id = 1;
            String str = String.valueOf(id);
            id_txt.setText(str);
            Connection con = ConnectionProvider.getCon();
            //Statement st = con.createStatement();
            Statement st = con.createStatement();
            String id_query = "SELECT MAX(id) FROM member";
            ResultSet rs = st.executeQuery(id_query);

            while (rs.next()) {
                id = rs.getInt(1);
                id = id + 1;
                String string = String.valueOf(id);
                id_txt.setText(string);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        id_txt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mobile_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gender_txt = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        father_txt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        amount_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        gymTime_txt = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        age_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nationalId_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        mother_txt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 118, 221));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_image/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 35, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 118, 221));
        jLabel2.setText("Member ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 113, -1, -1));

        id_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id_txt.setForeground(new java.awt.Color(255, 102, 102));
        id_txt.setText("00");
        jPanel1.add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 113, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 118, 221));
        jLabel4.setText("Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 148, -1, -1));

        name_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 176, 383, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 118, 221));
        jLabel5.setText("Mobile number:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 217, -1, -1));

        mobile_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mobile_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(mobile_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 245, 383, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 118, 221));
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 286, -1, -1));

        email_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 314, 383, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 118, 221));
        jLabel7.setText("Gender:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 355, -1, -1));

        gender_txt.setBackground(new java.awt.Color(0, 118, 221));
        gender_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender_txt.setForeground(new java.awt.Color(0, 118, 221));
        gender_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        jPanel1.add(gender_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 383, 383, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 118, 221));
        jLabel8.setText("Father's name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 424, -1, -1));

        father_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        father_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(father_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 452, 383, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 118, 221));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_image/save.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 512, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 118, 221));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_image/reset.png"))); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 512, -1, -1));

        amount_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        amount_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(amount_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 452, 383, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 118, 221));
        jLabel12.setText("Amount pay/month:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 424, -1, -1));

        gymTime_txt.setBackground(new java.awt.Color(0, 118, 221));
        gymTime_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gymTime_txt.setForeground(new java.awt.Color(0, 118, 221));
        gymTime_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00 AM - 12:00 PM", "03:00 PM - 09:00 PM" }));
        jPanel1.add(gymTime_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 383, 383, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 118, 221));
        jLabel10.setText("Gym time:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 355, -1, -1));

        age_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        age_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(age_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 314, 383, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 118, 221));
        jLabel9.setText("Age:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 286, -1, -1));

        nationalId_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nationalId_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(nationalId_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 245, 383, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 118, 221));
        jLabel13.setText("National ID:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 217, -1, -1));

        mother_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mother_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(mother_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 176, 383, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 118, 221));
        jLabel11.setText("Mother's name:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 148, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 118, 221));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_image/new member.png"))); // NOI18N
        jLabel1.setText("New Member");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 11, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        setBounds(100, 100, 1000, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new NewMember().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id = id_txt.getText();
        String name = name_txt.getText();
        String mobile = mobile_txt.getText();
        String email = email_txt.getText();
        String gender = (String) gender_txt.getSelectedItem();
        String father = father_txt.getText();
        String mother = mother_txt.getText();
        String nationalId = nationalId_txt.getText();
        String age = age_txt.getText();
        String gym_time = (String) gymTime_txt.getSelectedItem();
        String amount = amount_txt.getText();

        try {
            Connection con = ConnectionProvider.getCon();

            String insertQuery = "INSERT INTO member VALUES(?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement pst = con.prepareStatement(insertQuery);

            pst.setString(1, id);
            pst.setString(2, name);
            pst.setString(3, mobile);
            pst.setString(4, email);
            pst.setString(5, gender);
            pst.setString(6, father);
            pst.setString(7, mother);
            pst.setString(8, nationalId);
            pst.setString(9, age);
            pst.setString(10, gym_time);
            pst.setString(11, amount);

            int updatedRowCount = pst.executeUpdate();
            if (updatedRowCount > 0) {
                JOptionPane.showMessageDialog(null, "Successfully save");
                setVisible(false);
                new NewMember().setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Data failure");
            }

        } catch ( SQLException e) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewMember().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age_txt;
    private javax.swing.JTextField amount_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField father_txt;
    private javax.swing.JComboBox<String> gender_txt;
    private javax.swing.JComboBox<String> gymTime_txt;
    private javax.swing.JLabel id_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mobile_txt;
    private javax.swing.JTextField mother_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField nationalId_txt;
    // End of variables declaration//GEN-END:variables
}
