
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Computer Gallery
 */
public class Payment extends javax.swing.JFrame {

    public void tableDetails(){
        DefaultTableModel model = (DefaultTableModel) paymentTable.getModel();
        model.setRowCount(0); //always remove the row .after remove the info then new value is show
        
        String id = id_txt.getText();
        
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            String query = "SELECT * FROM `payment` WHERE id = '"+id+"'";
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()){
                model.addRow(new Object[]{
                    //only store date and payment.id don't need to store
                    rs.getString(2),
                    rs.getString(3)
                });
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    //for set payment date
    public void paymentDate(){
        SimpleDateFormat  dateFormat = new SimpleDateFormat("MMM-yyyy");
        Date date = new Date();
        String month =dateFormat.format(date);
        date_txt.setText(month);
    }
    
    public Payment() {
        initComponents();
        paymentDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveButton = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        date_txt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mobile_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        amount_txt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveButton.setBackground(new java.awt.Color(204, 255, 255));
        saveButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setForeground(new java.awt.Color(0, 118, 221));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_image/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        saveButton.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 118, 221));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_image/payment.png"))); // NOI18N
        jLabel1.setText("Payment");
        saveButton.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 19, 224, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 118, 221));
        jLabel2.setText("Member ID:");
        saveButton.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 113, -1, -1));

        id_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        id_txt.setForeground(new java.awt.Color(0, 118, 221));
        saveButton.add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 110, 70, -1));

        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(0, 118, 221));
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_image/search.png"))); // NOI18N
        searchButton.setText("search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        saveButton.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 118, 221));
        jLabel3.setText("Date:");
        saveButton.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 154, -1, -1));

        date_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        date_txt.setForeground(new java.awt.Color(0, 118, 221));
        date_txt.setText("mm:dd:yyyy");
        saveButton.add(date_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 154, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 118, 221));
        jLabel5.setText("Name:");
        saveButton.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 192, -1, -1));

        name_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name_txt.setForeground(new java.awt.Color(0, 118, 221));
        saveButton.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 224, 341, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 118, 221));
        jLabel6.setText("Mobile Number:");
        saveButton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 268, -1, -1));

        mobile_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mobile_txt.setForeground(new java.awt.Color(0, 118, 221));
        saveButton.add(mobile_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 300, 341, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 118, 221));
        jLabel7.setText("Email:");
        saveButton.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 344, -1, -1));

        email_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        email_txt.setForeground(new java.awt.Color(0, 118, 221));
        saveButton.add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 376, 341, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 118, 221));
        jLabel8.setText("Amount to pay:");
        saveButton.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 420, -1, -1));

        amount_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        amount_txt.setForeground(new java.awt.Color(0, 118, 221));
        saveButton.add(amount_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 458, 341, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 118, 221));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_image/save.png"))); // NOI18N
        jButton3.setText("Pay");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        saveButton.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 511, -1, -1));

        resetButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resetButton.setForeground(new java.awt.Color(0, 118, 221));
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_image/reset.png"))); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        saveButton.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 511, -1, -1));

        paymentTable.setForeground(new java.awt.Color(0, 118, 221));
        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Month", "Amount"
            }
        ));
        jScrollPane1.setViewportView(paymentTable);

        saveButton.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 110, -1, 450));

        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        setSize(new java.awt.Dimension(1000, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Payment().setVisible(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        tableDetails();
        int checkId = 0;
        String id = id_txt.getText();
        String month = date_txt.getText();
        
        try{
           Connection con = ConnectionProvider.getCon();
           Statement st = con.createStatement();
           String query = "SELECT * FROM `member` WHERE id = '"+id+"'";
           ResultSet rs = st.executeQuery(query);
           
           while(rs.next()){
               checkId = 1;
               id_txt.setEditable(false);
               name_txt.setText(rs.getString(2));
               mobile_txt.setText(rs.getString(3));
               email_txt.setText(rs.getString(4));
               amount_txt.setText(rs.getString(11));
           }
           if(checkId == 0 ){
               JOptionPane.showMessageDialog(null, "Member Id doesn't exits");
           }
           else{
               //now check member allready pay or not
            String query2 = "SELECT * FROM `payment` INNER JOIN member " +
 "WHERE payment.date='"+month+"' AND payment.id='"+id+"' AND member.id='"+id+"'";
            ResultSet rs1 = st.executeQuery(query2);
            while(rs1.next()){
                jButton3.setVisible(false);
                JOptionPane.showMessageDialog(null, "Payment is already done for this monthe");
            }
           }
           
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String id = id_txt.getText();
        String month = date_txt.getText();
        String amount = amount_txt.getText();
        
        try{
            Connection con = ConnectionProvider.getCon();
            String query = "INSERT INTO payment VALUES(?,?,?)";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, id);
            ps.setString(2, month);
            ps.setString(3, amount);
            
            ps.executeUpdate();
            tableDetails();
            JOptionPane.showMessageDialog(null, "Successfully updated");
            setVisible(false);
            new Payment().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Payment().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount_txt;
    private javax.swing.JLabel date_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mobile_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTable paymentTable;
    private javax.swing.JButton resetButton;
    private javax.swing.JPanel saveButton;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
