
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Computer Gallery
 */
public class Update_Delete_member extends javax.swing.JFrame {

    /**
     * Creates new form Update_Delete_member
     */
    public Update_Delete_member() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mobile_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        gender_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        father_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mother_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nationalId_tx = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        age_txt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        gym_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        amount_txt = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setForeground(new java.awt.Color(0, 118, 221));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_image/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 118, 221));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_image/update & delete member.png"))); // NOI18N
        jLabel1.setText("Update and Delete member");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 118, 221));
        jLabel2.setText("Member ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 96, -1, -1));

        id_txt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        id_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 93, 40, -1));

        searchButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(0, 118, 221));
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_image/search.png"))); // NOI18N
        searchButton.setText("search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 91, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 118, 221));
        jLabel3.setText("Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 135, -1, -1));

        name_txt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        name_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 164, 370, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 118, 221));
        jLabel4.setText("Mobile Number:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 211, -1, -1));

        mobile_txt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mobile_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(mobile_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 240, 370, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 118, 221));
        jLabel5.setText("Email:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 281, -1, -1));

        email_txt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        email_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 310, 370, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 118, 221));
        jLabel6.setText("Gender:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 357, -1, -1));

        gender_txt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        gender_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(gender_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 386, 370, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 118, 221));
        jLabel7.setText("Fathers Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 427, -1, -1));

        father_txt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        father_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(father_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 456, 370, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 118, 221));
        jLabel8.setText("Mothers Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 135, -1, -1));

        mother_txt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mother_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(mother_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 164, 370, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 118, 221));
        jLabel9.setText("National Id:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 211, -1, -1));

        nationalId_tx.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nationalId_tx.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(nationalId_tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 240, 370, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 118, 221));
        jLabel10.setText("Age:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 281, -1, -1));

        age_txt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        age_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(age_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 310, 370, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 118, 221));
        jLabel11.setText("Gym Time:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 357, -1, -1));

        gym_txt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        gym_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(gym_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 386, 370, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 118, 221));
        jLabel12.setText("Amount pay/month:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 427, -1, -1));

        amount_txt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        amount_txt.setForeground(new java.awt.Color(0, 118, 221));
        jPanel1.add(amount_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 456, 370, -1));

        updateButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(0, 118, 221));
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_image/save.png"))); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 518, -1, -1));

        deleteButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(0, 118, 221));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_image/delete.png"))); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 518, -1, -1));

        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 118, 221));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_image/reset.png"))); // NOI18N
        jButton5.setText("reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 518, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        setSize(new java.awt.Dimension(1000, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // For delete information:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to delete","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){ //a==0 means user selected id
            String id = id_txt.getText();
            try{
               Connection con = ConnectionProvider.getCon();
               Statement st = con.createStatement();
               String query = "DELETE FROM member WHERE id='"+id+"' ";
               st.executeUpdate(query);
               JOptionPane.showMessageDialog(null, "Deleted successfully");
               setVisible(false);
               new Update_Delete_member().setVisible(true);
            }
            catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Update_Delete_member().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // For search info by id wise
        int check_id=0;
        String id = id_txt.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            String query = "SELECT * FROM member WHERE id = '"+id+"' ";
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()){
                check_id = 1;
                id_txt.setEditable(false);//so that id can't change
                name_txt.setText(rs.getString(2));
                mobile_txt.setText(rs.getString(3));
                email_txt.setText(rs.getString(4));
                gender_txt.setText(rs.getString(5));
                father_txt.setText(rs.getString(6));
                mother_txt.setText(rs.getString(7));
                nationalId_tx.setText(rs.getString(8));
                age_txt.setText(rs.getString(9));
                gym_txt.setText(rs.getString(10));
                gym_txt.setEditable(false);
                amount_txt.setText(rs.getString(11));
            }
            if(check_id == 0){
                JOptionPane.showMessageDialog(null, "Memeber id doesn't exit");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // For updated database
        String id = id_txt.getText();
        String name = name_txt.getText();
        String mobile_number = mobile_txt.getText();
        String email = email_txt.getText();
        String gender = gender_txt.getText();
        String father_name = father_txt.getText();
        String mother_name = mother_txt.getText();
        String national_id = nationalId_tx.getText();
        String age = age_txt.getText();
        String gym_time = gym_txt.getText();
        String amount = amount_txt.getText();
        
        try{
            Connection con = ConnectionProvider.getCon();
            String query1 = "UPDATE member SET name=?,mobile_no=?,email=?,gender=?,father_name=?,mother_name=?,national_id=?,age=?,gym_time=?,amount=? where id=?";
            PreparedStatement ps = con.prepareStatement(query1);
            
            ps.setString(1, name);
            ps.setString(2, mobile_number);
            ps.setString(3, email);
            ps.setString(4, gender);
            ps.setString(5, father_name);
            ps.setString(6, mother_name);
            ps.setString(7, national_id);
            ps.setString(8, age);
            ps.setString(9,gym_time);
            ps.setString(10, amount);
            ps.setString(11, id);
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated successfully");
            setVisible(false);
            new Update_Delete_member().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Delete_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Delete_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Delete_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Delete_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Update_Delete_member().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age_txt;
    private javax.swing.JTextField amount_txt;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField father_txt;
    private javax.swing.JTextField gender_txt;
    private javax.swing.JTextField gym_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mobile_txt;
    private javax.swing.JTextField mother_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField nationalId_tx;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
